name: CI testing

# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  ci_testing:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install Poetry
        shell: bash
        run: |
          export POETRY_HOME=/opt/poetry
          python3 install-poetry.py --version 1.3.1
          $POETRY_HOME/bin/poetry --version

      - name: Install the dependencies and the package
        shell: bash
        run: |
          $POETRY_HOME/bin/poetry install --no-interaction -vvv --all-extras
          $POETRY_HOME/bin/poetry show

      - name: Tests
        run: |
          $POETRY_HOME/bin/poetry run pre-commit run --verbose
